debian:
  stage: test
  image: debian:stable
  before_script:
    - apt-get -qq update && apt-get -qq install -y python python-pip
    - pip install PyYAML
  script:
    - bash tests/run.sh break

archlinux:
  stage: test
  image: archlinux/base
  before_script:
    - pacman -Sy --noconfirm && pacman -S --noconfirm python python-pip
    - pip install PyYAML
  script:
    - bash tests/run.sh break
